### ISSUE TITLE
bamboo-sendgrid in bamboo core

### ISSUE THREAD

**Issue by paulcsmith** [mtwilliams/bamboo-sendgrid#6]
Hi @mtwilliams,

We just started a project where we need to use Sengrid and we need to do a number of tweaks and add some features to the Sengrid adapter, and we need to do it pretty quickly. We'd also like to add the adapter to core Bamboo. Since you did a lot of work on this original sengrid adapter, I plan to add a thank you and link to this original adapter since you did a lot of work on this. Does this plan sound ok to you?

**Comment by mtwilliams** [comment]
Appreciate you reaching out first, @paulcsmith.

I don't mind _per se_. However, having two disparate implementations makes little sense, so I would rather merge this into core and then delete this repository.

I can go ahead and submit a pull request that merges my work into core.

I'll also caveat that the code has not been tested in production workloads yet, i.e. there may be subtle bugs when dealing with SendGrid's real servers, though I have tried to maintaining a thorough test suite (that seems to be holding up.)

**Comment by mtwilliams** [comment]
Alternatively, I could just give you admin access to this repo.

**Comment by paulcsmith** [comment]
Yes you're right, having two implementations doesn't sound ideal. Can you submit a PR with the module doc set to false on the Sendgrid adapter until we've tested it all out in production? I think that would work well, and then we could add docs once it's tested and ready to go! :D

**Comment by mtwilliams** [comment]
Will do!

**Comment by paulcsmith** [comment]
I realized we can just do this ourselves since the code is open source (duh!), so no need to take time out of your day to open up a PR. I'll make sure to credit you as writing the initial implementation!

**Comment by mtwilliams** [comment]
Ah, a rewrite.

**Comment by paulcsmith** [comment]
Yeah it looks like there were some issues when we tried it out in production and we couldn't quite track down what was wrong so I think my coworker decided to try a different approach. I personally use Mandrill though so I'm not entirely sure what the problem was. 

Thanks for making this though. I think it provided some good guidance when he created the Sengrid adapter in Bamboo core.
